### ISSUE TITLE
Android project includes some local files

### ISSUE THREAD

**Issue by kantoniak** [killer-geckos/ivory-beam#9]
There's no `.gitignore` directly in `android/` and some extra files will get included. I didn't check thoroughly, but noticed the following:
* `android/local.properties`: `## This file must *NOT* be checked into Version Control Systems...`
* `android/gradle/wrapper/gradle-wrapper.jar`: I think IDE may download that jar, needs checking

Maybe it would be wise to pull `android/app/.gitignore` one dir up?

fyi @jakubpw

**Comment by avan1235** [comment]
- android/gradle/wrapper/gradle-wrapper.jar was not automatically ignored by the AndroidStudio while .gradle folder with temp file was, also other android projects on github have .jar file with gradle included
- android/local.properties will be removed
